export const LOGIN_MODAL = 'LOGIN_MODAL';
export const CLOCK_MODAL = 'CLOCK_MODAL';
export const CONFIGURE_POM_MODAL = 'CONFIGURE_POM_MODAL';
export const FINAL_PREVIEW_MODAL = 'FINAL_PREVIEW_MODAL';
